P0 badge button
Muzammil-khan710/Component-Library pull request #3
Opened 2022-02-09 18:17 UTC by Muzammil-khan710

Created Button and Badge components

2022-02-09 18:21 UTC, itsmebipul00 commented on docs/components/badge/badge.css
> +    height: 20px;
Try using rems

2022-02-09 18:32 UTC, itsmebipul00 approved these changes

2022-02-10 03:10 UTC, zoef-yt requested changes

2022-02-10 03:10 UTC, zoef-yt commented on docs/components/badge/badge.css
> +    border: 1px solid white;
use var for colour

2022-02-10 03:10 UTC, zoef-yt commented on docs/components/badge/badge.css
> +    border: 3px solid white;
use var for colour

2022-02-10 03:10 UTC, zoef-yt commented on docs/components/badge/badge.css
> +    border: 3px solid white;
use var for colour

2022-02-10 03:25 UTC, zoef-yt approved these changes
Good to merge.

2022-02-10 03:26 UTC, merged